article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('close/<int:id>',views.closeArticle,name = "close"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Madde Açan Kişi")
    title = models.CharField(max_length = 50,verbose_name = "Başlık")
    firma = models.CharField(max_length = 50, verbose_name= "Sorumlu Firma")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Fotoğraf Ekle")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

class CloseArticle(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="closeArticle", verbose_name="Kapanma Maddesi")
    close_author = models.ForeignKey("auth.User",on_delete=models.CASCADE, verbose_name = "Maddeyi Kapatan Kişi")
    close_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    close_image = models.FileField(blank = True,null = True,verbose_name="Fotoğraf Ekle")
    close_date = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Makale",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article, CloseArticle
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","firma","content","article_image"]

class CloseForm(forms.ModelForm):
    class Meta:
        model = CloseArticle
        fields = ["close_content","close_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm, CloseForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})
def index(request):
    articles = Article.objects.all()
    """closes = articles.closeArticle.all()"""
    """context_close = {
        "closes":closes
    }"""
    context = {
        "articles":articles
    }
    return render(request,"index.html",context)
    
def about(request):
    return render(request,"about.html")
@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Madde başarıyla oluşturuldu")
        return redirect("article:dashboard")
    return render(request,"addarticle.html",{"form":form})

def detail(request,id):
    article = get_object_or_404(Article,id = id)

    comments = article.comments.all()

    closes = article.closeArticle.all()

    return render(request,"detail.html",{"article":article,"comments":comments, "closes":closes})

@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla güncellendi")
        return redirect("article:dashboard")


    return render(request,"update.html",{"form":form})
@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Makale Başarıyla Silindi")

    return redirect("article:dashboard")
def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

def closeArticle(request,id):
    article = get_object_or_404(Article, id = id)
    form = CloseForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        closeArticle = form.save(commit=False)
        closeArticle.article = article
        closeArticle.close_author = request.user
        closeArticle.save()
        messages.success(request,"Madde başarıyla kapatıldı.")
        return redirect("article:articles")
    
    return render(request,"close.html", {"article":article, "form":form})
    

templates/about.html
{% extends "layout.html" %}


{% block body %}

<h3>Hakkımızda</h3>
<hr>

<p>VOME Ekibi olarak gelecek projelerde çalıştığımız firmalar ile iş takibimizi daha yalın ve aktif bir şekilde yapabilmek için böyle bir platform geliştridik. Bu platformun asıl amacı manuel olarak tutulan PTTR' listelerinin şeffaf bir şekilde herkes tarafından okunabilmesi, herkesin problem tespit edip buraya girebilmesi, ve otomatik raporlama yapabilmesidir.</p>
<p>Yapacağımız bu site ile beraber projelerimizdeki problemlerin tespitini ve takibini kolaylaştırmayı planlıyoruz.<p>
</p>Sizlerin de bizlere olacak desteği için şimdiden teşekkür ederiz.</p>
        

        

{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Madde Ekle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Madde Ekle</button>
        </form>
    </div>
  </div>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class ="row">
    
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <h3>PTTR Maddeleri</h3>
                <hr>
                </div>
        </div>
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form>
                 {% csrf_token %} 
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
              <button type="submit" class="btn btn-danger">Ara</button>
            </form>
      </div>
    </div>

</div>


{% if articles %}

{% for article in articles %}
<div class="row">
    <div class="col-md-10 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a> 
        
      <!-- Author -->
      <p class="lead">
        
        {{article.author.username}} tarafından yayınlandı
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>
      <hr>
      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe|truncatewords:50}}
      </p>

      <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">Devamını Oku</a>
      <hr>
         
        </div>
      </div>
      </div>

{% endfor %}


{% else %}

<div class ="row">
    
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
          <br>
<div class = "alert alert-danger">
   Madde Bulunamadı
</div>
</div>
</div>
</div>
{% endif %}

{% endblock body %}

templates/close.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">
        
        {{article.author.username}} tarafından yayınlandı
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe}}
      </p>

      <hr>

      <h4>Madde Kapat</h4>
      <hr>
                <form method = "post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
                    {{form.media}}
                    <br>
                    <button type = "submit" class = "btn btn-danger">Madde Kapat</button>
                </form>
            </div>
        </div>
     

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a class = "btn btn-primary" href = "{% url 'article:addarticle' %}">Madde Ekle </a>
<hr>
{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Firma</th>
            <th scope="col">Tarih</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Maddeyi Kapat</th>
            <th scope="col">Sil</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.firma}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class = "btn btn-primary">Güncelle</a></td>
            <td><a href="{% url 'article:close' article.id %}" class = "btn btn-success">Maddeyi Kapat</a> </td>
            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Sil</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
{% else %}

<div class = "alert alert-danger">
    Açık madde bulunmamaktadır...

</div>
{% endif %}



{% endblock body %}


templates/detail.html
{% extends "layout.html" %}

{% block body %}
  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">
        
        {{article.author.username}} tarafından yayınlandı
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe}}
      </p>

      <hr>

      <h4>Kapanma Maddeleri</h4>
      <hr>
      {%if closes %}
        {% for close in closes  %}
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{close.close_author}}</h5>
              {{close.close_date}} <br>
              {{close.close_content}}
              {% if close.close_image %}
              <img class="img-fluid rounded" src="{{close.close_image.url}}" alt="">
              {% endif %}
            </div>
          </div>
        {% endfor %}
      {% else %}
        <div class ="alert alert-danger">
          Madde hala açık durumda!
        </div>
      {% endif %}

      <h4>Yorumlar</h4>
      <hr>
      {% if comments %}
        {% for comment in comments  %}
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{comment.comment_author}}</h5>
              {{comment.comment_date}} <br>
              {{comment.comment_content}}
            </div>
          </div>
        {% endfor %}

      {% else %}

      <div class ="alert alert-info">
        İlk yorum yapan siz olun!
      </div>

      {% endif %}

      <div class="card my-4">
          <h5 class="card-header">Yorum Ekle:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
                <div class="form-group">
                  <label for="formGroupExampleInput">İsim</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi girin">
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput">Yorum</label>
                  <textarea name = "comment_content" class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Ekle</button>
                </form>
            </div>
          </div>
      </div>
  </div>

      

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}


<div class="jumbotron text-center">
        <h3>PTTR Sitemize Hoş Geldiniz..</h3>
        <p>Bu sitede projelerimiz ile ilgili problemleri firmalara atayabilir ve kontrolleri site üzerinden yürütebilirsiniz.
        </p>
</div>


{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Firma</th>
            <th scope="col">Tarih</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Maddeyi Kapat</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.firma}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class = "btn btn-primary">Güncelle</a></td>
            <td><a href="{% url 'article:close' article.id %}" class = "btn btn-success">Maddeyi Kapat</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
{% else %}

<div class = "alert alert-danger">
    Açık madde bulunmamaktadır...

</div>
{% endif %}


{% endblock body %}


templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>FO PTTR</title>
</head>
<body>  
        {% include "includes/navbar.html" %}

        

        <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">
                
            {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}
            {% block body %}
            
            {% endblock body %}

        </div>

        
      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

    
      {% include "includes/navbar-bottom.html" %}
  
    </body>

</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-primary">Giriş Yap</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-primary">Kayıt Ol</button>
        </form>
    </div>
  </div>

{% endblock body %}


templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Madde Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-primary">Madde Güncelle</button>
        </form>
    </div>
  </div>


{% endblock body %}